VodPlatform/Controllers/VideoPlayerController.cs
using Microsoft.AspNetCore.Mvc;
using VodPlatform.Services;

namespace VodPlatform.Controllers
{
    public class VideoPlayerController : Controller
    {
        private readonly VideoServices _videoServices;

        public VideoPlayerController(VideoServices videoServices)
        {
            _videoServices = videoServices;
        }

 

        public async Task<IActionResult> MoviesList()
        {
            return View(await _videoServices.ListMovies());  
        }


        [HttpGet("watch/{movieName}")]
        public IActionResult WatchMovie(string movieName)
        {
            ViewBag.Movie = movieName;
            return View();
        }


        [HttpGet("stream/{movieName}/{file}")]
        public async Task<IActionResult> Stream(string movieName, string file)
        {
            return await _videoServices.SendData(movieName, file);
        }


    }
}

VodPlatform/Views/VideoPlayer/MoviesList.cshtml
@model List<string>
@{
    ViewData["Title"] = "Movie List";
}

<h1>Movie List</h1>

@if (Model != null && Model.Any())
{
    <ul>
        @foreach (var movie in Model)
        {
            <li>
                <a href="@Url.Action("WatchMovie", "VideoPlayer", new { movieName = movie })">
                    @movie
                </a>
            </li>
        }
    </ul>
}
else
{
    <p>No available movies.</p>
}

VodPlatform/Views/VideoPlayer/WatchMovie.cshtml
@section Styles {
    <link rel="stylesheet" href="~/css/videoplayer.css" />
}

@{
    ViewBag.Title = ViewBag.Movie;
}

<div class="video-container">
    <video id="player" controls crossorigin playsinline>
        <source src="@Url.Action("Stream", "VideoPlayer", new { movieName = ViewBag.Movie, file = "output.mpd" })" type="application/dash+xml">
        Your browser does not support the video tag.
    </video>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const player = new Plyr('#player', {
                controls: [
                    'play', 'progress', 'current-time', 'duration', 'mute', 'volume', 'captions', 'settings', 'fullscreen'
                ],
                settings: ['captions', 'speed'],
                i18n: { speed: 'Speed' }
            });
        });
    </script>
}